openapi: "3.0.3"
info:
  title: TARDIS Reality API
  version: 1.0.0
servers:
  - url: http://192.168.1.161
    description: Production Server
paths:
  /api/led/color:
    post:
      operationId: updateLedColor
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LedColorPayload'
      responses:
        '200':
          description: Successfully updated color
components:
  schemas:
    LedColorPayload:
      type: object
      properties:
        part_name:
          type: string
          description: The name of the TARDIS part (e.g. 'hull', 'top_light')
        red:
          type: integer
        green:
          type: integer
        blue:
          type: integer
      required:
        - part_name
        - red
        - green
        - blue
